version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-react-app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
